name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle

        run: mkdir -p /root/.gradle && \
          echo -e "systemProp.http.proxyHost=krmp-proxy.9rum.cc\nsystemProp.http.proxyPort=3128\nsystemProp.https.proxyHost=krmp-proxy.9rum.cc\nsystemProp.https.proxyPort=3128" > /root/.gradle/gradle.properties && \
          chmod +x gradlew && ./gradlew build -x test

      - name: Build Docker Image
        run: |
          docker build -t test-app:latest .
          docker tag test-app:latest username/test-app:latest

      - name: Test
        run: docker run test-app:latest ./gradlew test

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: username/test-app
          tag_with_ref: true

      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          args: apply -f backend.yaml
