name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle

        run: chmod +x gradlew && ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t test-app:latest .
          docker tag test-app:latest ${{ secrets.DOCKER_USERNAME }}/test-app:latest

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test-app:latest

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST https://kac33671a015da.user-app.krampoline.com/view/all/newJob/buildByToken/build?job=cd \
          --user admin:113f77a4929030c5920e2d70bae7f91e78 \
          --data-urlencode json='{"parameter": [{"name":"PARAM_NAME", "value":"PARAM_VALUE"}]}'
     
